# Generated by Django 4.2.3 on 2023-08-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_text',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_depth',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_status',
            field=models.CharField(choices=[('Y', '일반 댓글'), ('N', '비밀 댓글')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='reply',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
    ]
