# Generated by Django 4.2.3 on 2023-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=50, unique=True)),
                ('user_address', models.TextField()),
                ('user_language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
